model_class: qdl.models.classifiers.cnn_qlstm_classifier.CNNQLSTMClassifier
is_lstm_quantum: false
is_cnn_quantum: true
lstm:
  input_size: 4
  hidden_size: 4
  batch_first: true
quanv:
  quanvolution_type: rx-cnot
  rx_cnot:
    init_params: 0 # null to initialize U[-pi, pi]
  stride: 2
  # n_blocks: 2
  out_channels: 1
  # n_ops: 8
conv2d:
  in_channels: 1
  out_channels: 4
  stride: 2
  kernel_size: 2
last_linear_layer:
  in_features: 4 # QLSTM hidden size
  out_features: 4 # 4 classes
metrics:
  task: "multiclass"
  num_classes: 4
logger:
  log_grads: true
optim:
  use_cosine_annealing: false
  lr: 1e-3
  weight_decay: 1e-1
  beta1: 0.9
  beta2: 0.95